<?php

namespace De\Idrinth\Travian;

interface Troops
{
    public const CORN = [
        'hero' => 6,
        'roman_soldier1' => 1,
        'roman_soldier2' => 1,
        'roman_soldier3' => 1,
        'roman_soldier4' => 2,
        'roman_soldier5' => 3,
        'roman_soldier6' => 4,
        'gaul_soldier1' => 1,
        'gaul_soldier2' => 1,
        'gaul_soldier3' => 2,
        'gaul_soldier4' => 2,
        'gaul_soldier5' => 2,
        'gaul_soldier6' => 3,
        'teuton_soldier1' => 1,
        'teuton_soldier2' => 1,
        'teuton_soldier3' => 1,
        'teuton_soldier4' => 1,
        'teuton_soldier5' => 2,
        'teuton_soldier6' => 3,
        'hun_soldier1' => 1,
        'hun_soldier2' => 1,
        'hun_soldier3' => 2,
        'hun_soldier4' => 2,
        'hun_soldier5' => 2,
        'hun_soldier6' => 3,
        'egyptian_soldier1' => 1,
        'egyptian_soldier2' => 1,
        'egyptian_soldier3' => 1,
        'egyptian_soldier4' => 2,
        'egyptian_soldier5' => 2,
        'egyptian_soldier6' => 3,
    ];
    public const SPEED = [
        'hero' => 7,
        'roman_soldier1' => 6,
        'roman_soldier2' => 5,
        'roman_soldier3' => 7,
        'roman_soldier4' => 16,
        'roman_soldier5' => 14,
        'roman_soldier6' => 10,
        'roman_settler' => 5,
        'roman_chief' => 4,
        'roman_ram' => 4,
        'roman_catapult' => 3,
        'gaul_soldier1' => 7,
        'gaul_soldier2' => 6,
        'gaul_soldier3' => 17,
        'gaul_soldier4' => 19,
        'gaul_soldier5' => 16,
        'gaul_soldier6' => 13,
        'gaul_settler' => 5,
        'gaul_chief' => 4,
        'gaul_ram' => 4,
        'gaul_catapult' => 3,
        'teuton_soldier1' => 7,
        'teuton_soldier2' => 7,
        'teuton_soldier3' => 6,
        'teuton_soldier4' => 9,
        'teuton_soldier5' => 10,
        'teuton_soldier6' => 9,
        'teuton_settler' => 5,
        'teuton_chief' => 4,
        'teuton_ram' => 4,
        'teuton_catapult' => 3,
        'hun_soldier1' => 6,
        'hun_soldier2' => 6,
        'hun_soldier3' => 19,
        'hun_soldier4' => 16,
        'hun_soldier5' => 16,
        'hun_soldier6' => 14,
        'hun_settler' => 5,
        'hun_chief' => 5,
        'hun_ram' => 4,
        'teuton_catapult' => 3,
        'egyptian_soldier1' => 7,
        'egyptian_soldier2' => 6,
        'egyptian_soldier3' => 7,
        'egyptian_soldier4' => 16,
        'egyptian_soldier5' => 15,
        'egyptian_soldier6' => 10,
        'egyptian_settler' => 5,
        'egyptian_chief' => 4,
        'egyptian_ram' => 4,
        'egyptian_catapult' => 3,
    ];
}
