<?php

namespace De\Idrinth\Travian;

interface Troops
{
    public const SCOUTS = [
        'roman_soldier4',
        'gaul_soldier3',
        'teuton_soldier4',
        'hun_soldier3',
        'egyptian_soldier4',
    ];
    public const OFF = [
        'roman_soldier3',
        'roman_soldier5',
        'roman_soldier6',
        'gaul_soldier2',
        'gaul_soldier4',
        'gaul_soldier6',
        'teuton_soldier1',
        'teuton_soldier3',
        'teuton_soldier6',
        'hun_soldier1',
        'hun_soldier2',
        'hun_soldier4',
        'hun_soldier5',
        'hun_soldier6',
        'egyptian_soldier3',
        'egyptian_soldier6',
    ];
    public const DEFF = [
        'roman_soldier1',
        'roman_soldier2',
        'roman_soldier6',
        'gaul_soldier1',
        'gaul_soldier5',
        'gaul_soldier6',
        'teuton_soldier1',
        'teuton_soldier2',
        'teuton_soldier3',
        'teuton_soldier4',
        'teuton_soldier5',
        'teuton_soldier6',
        'hun_soldier1',
        'hun_soldier5',
        'egyptian_soldier1',
        'egyptian_soldier2',
        'egyptian_soldier5',
        'egyptian_soldier6',
    ];
    public const CORN = [
        'hero' => 6,
        'roman_soldier1' => 1,
        'roman_soldier2' => 1,
        'roman_soldier3' => 1,
        'roman_soldier4' => 2,
        'roman_soldier5' => 3,
        'roman_soldier6' => 4,
        'roman_ram' => 3,
        'roman_catapult' => 6,
        'gaul_soldier1' => 1,
        'gaul_soldier2' => 1,
        'gaul_soldier3' => 2,
        'gaul_soldier4' => 2,
        'gaul_soldier5' => 2,
        'gaul_soldier6' => 3,
        'gaul_ram' => 3,
        'gaul_catapult' => 6,
        'teuton_soldier1' => 1,
        'teuton_soldier2' => 1,
        'teuton_soldier3' => 1,
        'teuton_soldier4' => 1,
        'teuton_soldier5' => 2,
        'teuton_soldier6' => 3,
        'teuton_ram' => 3,
        'teuton_catapult' => 6,
        'hun_soldier1' => 1,
        'hun_soldier2' => 1,
        'hun_soldier3' => 2,
        'hun_soldier4' => 2,
        'hun_soldier5' => 2,
        'hun_soldier6' => 3,
        'hun_ram' => 3,
        'hun_catapult' => 6,
        'egyptian_soldier1' => 1,
        'egyptian_soldier2' => 1,
        'egyptian_soldier3' => 1,
        'egyptian_soldier4' => 2,
        'egyptian_soldier5' => 2,
        'egyptian_soldier6' => 3,
        'egyptian_ram' => 3,
        'egyptian_catapult' => 6,
    ];
    public const SPEED = [
        'hero' => 7,
        'roman_soldier1' => 6,
        'roman_soldier2' => 5,
        'roman_soldier3' => 7,
        'roman_soldier4' => 16,
        'roman_soldier5' => 14,
        'roman_soldier6' => 10,
        'roman_settler' => 5,
        'roman_chief' => 4,
        'roman_ram' => 4,
        'roman_catapult' => 3,
        'gaul_soldier1' => 7,
        'gaul_soldier2' => 6,
        'gaul_soldier3' => 17,
        'gaul_soldier4' => 19,
        'gaul_soldier5' => 16,
        'gaul_soldier6' => 13,
        'gaul_settler' => 5,
        'gaul_chief' => 4,
        'gaul_ram' => 4,
        'gaul_catapult' => 3,
        'teuton_soldier1' => 7,
        'teuton_soldier2' => 7,
        'teuton_soldier3' => 6,
        'teuton_soldier4' => 9,
        'teuton_soldier5' => 10,
        'teuton_soldier6' => 9,
        'teuton_settler' => 5,
        'teuton_chief' => 4,
        'teuton_ram' => 4,
        'teuton_catapult' => 3,
        'hun_soldier1' => 6,
        'hun_soldier2' => 6,
        'hun_soldier3' => 19,
        'hun_soldier4' => 16,
        'hun_soldier5' => 16,
        'hun_soldier6' => 14,
        'hun_settler' => 5,
        'hun_chief' => 5,
        'hun_ram' => 4,
        'teuton_catapult' => 3,
        'egyptian_soldier1' => 7,
        'egyptian_soldier2' => 6,
        'egyptian_soldier3' => 7,
        'egyptian_soldier4' => 16,
        'egyptian_soldier5' => 15,
        'egyptian_soldier6' => 10,
        'egyptian_settler' => 5,
        'egyptian_chief' => 4,
        'egyptian_ram' => 4,
        'egyptian_catapult' => 3,
    ];
    public const INFANTRY_DEFF = [
        'roman_soldier1' => 35,
        'roman_soldier2' => 65,
        'roman_soldier3' => 40,
        'roman_soldier4' => 20,
        'roman_soldier5' => 65,
        'roman_soldier6' => 80,
        'gaul_soldier1' => 40,
        'gaul_soldier2' => 35,
        'gaul_soldier3' => 20,
        'gaul_soldier4' => 25,
        'gaul_soldier5' => 115,
        'gaul_soldier6' => 60,
        'teuton_soldier1' => 20,
        'teuton_soldier2' => 35,
        'teuton_soldier3' => 30,
        'teuton_soldier4' => 10,
        'teuton_soldier5' => 100,
        'teuton_soldier6' => 50,
        'hun_soldier1' => 40,
        'hun_soldier2' => 30,
        'hun_soldier3' => 20,
        'hun_soldier4' => 30,
        'hun_soldier5' => 80,
        'hun_soldier6' => 60,
        'egyptian_soldier1' => 30,
        'egyptian_soldier2' => 55,
        'egyptian_soldier3' => 50,
        'egyptian_soldier4' => 20,
        'egyptian_soldier5' => 110,
        'egyptian_soldier6' => 120,
    ];
    public const CAVALRY_DEFF = [
        'roman_soldier1' => 50,
        'roman_soldier2' => 35,
        'roman_soldier3' => 25,
        'roman_soldier4' => 10,
        'roman_soldier5' => 50,
        'roman_soldier6' => 105,
        'gaul_soldier1' => 50,
        'gaul_soldier2' => 20,
        'gaul_soldier3' => 10,
        'gaul_soldier4' => 40,
        'gaul_soldier5' => 55,
        'gaul_soldier6' => 165,
        'teuton_soldier1' => 5,
        'teuton_soldier2' => 60,
        'teuton_soldier3' => 30,
        'teuton_soldier4' => 5,
        'teuton_soldier5' => 40,
        'teuton_soldier6' => 75,
        'hun_soldier1' => 30,
        'hun_soldier2' => 10,
        'hun_soldier3' => 20,
        'hun_soldier4' => 15,
        'hun_soldier5' => 70,
        'hun_soldier6' => 40,
        'egyptian_soldier1' => 20,
        'egyptian_soldier2' => 40,
        'egyptian_soldier3' => 20,
        'egyptian_soldier4' => 10,
        'egyptian_soldier5' => 50,
        'egyptian_soldier6' => 150,
    ];
}
